import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import { use, useEffect, useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

interface IDetails {
  id: number,
  first_name: string,
  last_name: string,
  password: string,
  gender: string,
  email: string,
  country: string,
  city: string,
  zip: number,
  created_at: string,
  updated_at: string,
  interest: string[],
  picture: any
}

function BlobToText({ blob } : { blob : Blob}) {

  // let base64data: string | ArrayBuffer = "";
  
  // const reader = new FileReader();
  // reader.readAsDataURL(blob);
  // reader.onload = () => {
  //   base64data = reader.result!;
  // }
  
  // return <Image src={base64data} alt="" height={64} width={64} />;
}

export default function Home() {

  const [details, setDetails] = useState<IDetails[] | null>();
  const [loaded, setLoaded] = useState(false);

  async function getData() {
    const res = await fetch("http://localhost:8080/getAllUsers");
    const data = await res.json();
    setDetails(data);

    res.ok && setLoaded(true);
  }

  useEffect(() => {
    getData();
    
    if (loaded) {
      const data = details![4].picture.data;
      const bug = Buffer.from(data);
      const str = bug.toString();
      
    }
    
    
  }, [loaded]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <nav><Link href={"/SignUp"}>Sign Up</Link></nav>
        <div className={styles.table}>
          <TableContainer component={Paper}>
            <Table sx={{ minWidth: 650 }} aria-label="simple table">
              <TableHead>
                <TableRow>
                  <TableCell>Profile Picture</TableCell>
                  <TableCell>First Name</TableCell>
                  <TableCell>Second Name</TableCell>
                  <TableCell align="right">Email</TableCell>
                  <TableCell align="right">Gender</TableCell>
                  <TableCell align="right">Country</TableCell>
                  <TableCell align="right">City</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {details && details.map((detail) => (
                  <TableRow
                    key={detail.id}
                    sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                  >
                    <TableCell component="th" scope="row">
                      {/* <img src={"data:" + detail.picture} height={64} width={64} alt="" /> */}
                      <img src={(detail.picture.data).buffer} height={64} width={64} alt="" />
                      {/* <BlobToText blob={detail.picture} /> */}
                    </TableCell>
                    <TableCell component="th" scope="row">
                      {detail.first_name}
                    </TableCell>
                    <TableCell component="th" scope="row">
                      {detail.last_name}
                    </TableCell>
                    <TableCell align="right">{detail.email}</TableCell>
                    <TableCell align="right">{detail.gender}</TableCell>
                    <TableCell align="right">{detail.country}</TableCell>
                    <TableCell align="right">{detail.city}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </div>
      </main>
    </>
  );
}
